Repository heroku/buildpacks-nodejs, pull requests merged in 2021-02, with the labels that each got.

#15 copy node modules dir path into env
  buildpacks/nodejs/CHANGELOG.md
  buildpacks/nodejs/bin/build
  buildpacks/nodejs/lib/build.sh
  buildpacks/nodejs/shpec/build_shpec.sh
Labels: languages-review

#24 Readd heroku-18 test
  .circleci/config.yml
Labels: skip changelog

#26 bump version so it does not collide with the pack-images meta buildpack
  meta-buildpacks/nodejs/CHANGELOG.md
  meta-buildpacks/nodejs/buildpack.toml
Labels: languages-review, skip changelog
