Repository heroku/buildpacks-nodejs, pull requests merged in 2023-08, with the labels that each got.

#610 Rename CNB release metadata
  buildpacks/nodejs-corepack/buildpack.toml
  buildpacks/nodejs-engine/buildpack.toml
  buildpacks/nodejs-function-invoker/buildpack.toml
  buildpacks/nodejs-pnpm-install/buildpack.toml
  buildpacks/nodejs-yarn/buildpack.toml
  buildpacks/npm/buildpack.toml
  meta-buildpacks/nodejs-function/buildpack.toml
  meta-buildpacks/nodejs/buildpack.toml
Labels: skip changelog

#609 Update release.yml to use the new combined release workflow
  .github/workflows/release.yml
Labels: skip changelog

#611 Use stable workflow release
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
Labels: skip changelog

#612 Configure npm distribution mirror and inventory syncing
  .github/workflows/_mirror-distribution.yml
  .github/workflows/_update-inventory.yml
  .github/workflows/inventory.yml
  .github/workflows/mirror.yml
  buildpacks/nodejs-npm-engine/CHANGELOG.md
  buildpacks/nodejs-npm-engine/inventory.toml
  common/bin/download-verify-npm-package
  common/nodejs-utils/src/bin/diff_versions.rs
  common/nodejs-utils/src/bin/generate_inventory.rs
  common/nodejs-utils/src/bin/list_unmirrored_versions.rs
  common/nodejs-utils/src/distribution.rs
  common/nodejs-utils/src/inv.rs
  common/nodejs-utils/src/npmjs_org.rs
  common/nodejs-utils/src/s3.rs
Labels: enhancement, skip changelog, automation, rust

#617 Support yarn 2.4.3
  common/bin/download-verify-npm-package
Labels: bug, skip changelog, automation

#621 Fix inventory update order
  common/nodejs-utils/src/bin/diff_versions.rs
Labels: bug, skip changelog, automation

#627 Ignore yarn 2.4.3
  common/bin/download-verify-npm-package
  common/nodejs-utils/src/distribution.rs
Labels: bug, skip changelog

#638 Update to libcnb 0.14.0
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  buildpacks/nodejs-corepack/tests/integration_test.rs
  buildpacks/nodejs-engine/tests/integration_test.rs
  test_support/src/lib.rs
Labels: skip changelog

#628 Skip `mirror-distribution` job if there are no versions
  .github/workflows/_mirror-distribution.yml
Labels: bug, skip changelog, automation
