Repository heroku/buildpacks-nodejs, pull requests merged in 2024-05, with the labels that each got.

#814 Use artifact inventory
  .github/workflows/inventory.yml
  Cargo.lock
  buildpacks/nodejs-engine/Cargo.toml
  buildpacks/nodejs-engine/inventory.toml
  buildpacks/nodejs-engine/src/layers/dist.rs
  buildpacks/nodejs-engine/src/main.rs
  buildpacks/nodejs-engine/tests/integration_test.rs
  common/nodejs-utils/Cargo.toml
  common/nodejs-utils/src/bin/update_node_inventory.rs
  common/nodejs-utils/src/lib.rs
  common/nodejs-utils/src/vrs.rs
Labels: skip changelog, rust

#815 Add linux/arm64 targets
  buildpacks/nodejs-corepack/CHANGELOG.md
  buildpacks/nodejs-corepack/buildpack.toml
  buildpacks/nodejs-engine/CHANGELOG.md
  buildpacks/nodejs-engine/buildpack.toml
  buildpacks/nodejs-function-invoker/CHANGELOG.md
  buildpacks/nodejs-function-invoker/buildpack.toml
  buildpacks/nodejs-npm-engine/CHANGELOG.md
  buildpacks/nodejs-npm-engine/buildpack.toml
  buildpacks/nodejs-npm-install/CHANGELOG.md
  buildpacks/nodejs-npm-install/buildpack.toml
  buildpacks/nodejs-pnpm-engine/CHANGELOG.md
  buildpacks/nodejs-pnpm-engine/buildpack.toml
  buildpacks/nodejs-pnpm-install/CHANGELOG.md
  buildpacks/nodejs-pnpm-install/buildpack.toml
  buildpacks/nodejs-yarn/CHANGELOG.md
  buildpacks/nodejs-yarn/buildpack.toml
  meta-buildpacks/nodejs/CHANGELOG.md
Labels: enhancement

#835 Add release key for new Node maintainer
  common/bin/download-verify-node
Labels: skip changelog

#839 Fixed the changelog to follow the Keep a Changelog spec properly
  buildpacks/nodejs-engine/CHANGELOG.md
Labels: skip changelog

#841 Adding Heroku-24 to CI test matrix
  .github/workflows/ci.yml
  buildpacks/nodejs-engine/src/layers/dist.rs
  buildpacks/nodejs-engine/tests/integration_test.rs
  buildpacks/nodejs-npm-install/tests/fixtures/npm-project-with-native-module/package-lock.json
  buildpacks/nodejs-npm-install/tests/fixtures/npm-project-with-native-module/package.json
  buildpacks/nodejs-npm-install/tests/integration_test.rs
  buildpacks/nodejs-pnpm-install/tests/fixtures/pnpm-project-with-native-module/package.json
  buildpacks/nodejs-pnpm-install/tests/fixtures/pnpm-project-with-native-module/pnpm-lock.yaml
  buildpacks/nodejs-pnpm-install/tests/integration_test.rs
  buildpacks/nodejs-yarn/tests/fixtures/yarn-project-with-native-module/.editorconfig
  buildpacks/nodejs-yarn/tests/fixtures/yarn-project-with-native-module/.gitattributes
  buildpacks/nodejs-yarn/tests/fixtures/yarn-project-with-native-module/.gitignore
  buildpacks/nodejs-yarn/tests/fixtures/yarn-project-with-native-module/README.md
  buildpacks/nodejs-yarn/tests/fixtures/yarn-project-with-native-module/package.json
  buildpacks/nodejs-yarn/tests/fixtures/yarn-project-with-native-module/yarn.lock
  buildpacks/nodejs-yarn/tests/integration_test.rs
  test_support/src/lib.rs
Labels: skip changelog

#843 Fix Node.js inventory automation
  .github/workflows/inventory.yml
Labels: skip changelog

#847 Fix failing integration test
  buildpacks/nodejs-pnpm-install/tests/integration_test.rs
Labels: skip changelog

#838 Add `#[serde(deny_unknown_fields)]` to structs
  buildpacks/nodejs-corepack/src/layers/manager.rs
  buildpacks/nodejs-corepack/src/layers/shim.rs
  buildpacks/nodejs-engine/src/layers/dist.rs
  buildpacks/nodejs-function-invoker/src/layers/runtime.rs
  buildpacks/nodejs-function-invoker/src/main.rs
  buildpacks/nodejs-npm-engine/src/layers/npm_engine.rs
  buildpacks/nodejs-npm-install/src/layers/npm_cache.rs
  buildpacks/nodejs-pnpm-install/src/layers/addressable_store.rs
  buildpacks/nodejs-yarn/src/layers/cli.rs
  buildpacks/nodejs-yarn/src/layers/deps.rs
  buildpacks/nodejs-yarn/src/yarn.rs
Labels: skip changelog

#852 Use pub-hk-ubuntu-22.04-arm-small
  .github/workflows/ci.yml
Labels: skip changelog

#853 Drop unnecessary installs for arm64 from workflow
  .github/workflows/ci.yml
Labels: skip changelog
